### ISSUE TITLE
Change Blog links

### ISSUE THREAD

**Issue by watahani** [cssjpn/cssjpn.github.io#1]
- [x] DSI: https://jpdsi.github.io/blog/​
- [x] Azure Identity: https://jpazureid.github.io/blog/​ -> https://aka.ms/jpazureid
- [x] IaaS: https://jpaztech.github.io/blog/

**Comment by watahani** [comment]
fixed https://aka.ms/jpazureid

**Comment by akkomats** [comment]
- [ ] SharePoint: [https://jpspsupport.github.io/blog/](https://jpspsupport.github.io/blog/)
