### ISSUE TITLE
[Request] Add the Link of Power BI Support Team Blog

### ISSUE THREAD

**Issue by Hyamyam** [cssjpn/cssjpn.github.io#11]
[Japan CSS Support Power BI Blog](https://jpbap-sqlbi.github.io/blog/)
日本マイクロソフトPower BIサポートチームのブログです。チームの担当製品である Power BI の情報を中心にお届けします。

![Power BI Logo_m](https://user-images.githubusercontent.com/73410575/127790835-fd4bdecd-f026-48fb-9e30-f8f63fec1d32.png)

**Comment by watahani** [comment]
see #13
