### ISSUE TITLE
Change Blog link for Dynamics 365 Finance and Operations

### ISSUE THREAD

**Issue by Tad1011** [cssjpn/cssjpn.github.io#20]
Dynamics 365 Finance and OperationsのBlogリンクを以下のURLへ変更をお願いいたします。
Dynamics 365 Finance and Operations: https://jpdynamicserp.github.io/blog/

**Comment by juntakata** [comment]
お知らせありがとうございます。以下のように変更いたしました。その他にもありましたらお知らせください。

New: https://jpdynamicserp.github.io/blog/
Old: https://blogs.msdn.microsoft.com/axjapan/
