### ISSUE TITLE
Add the Link of Unified Communications  Support Team Blog

### ISSUE THREAD

**Issue by aksuyari** [cssjpn/cssjpn.github.io#6]
[Unified Communications  サポート チーム](https://jpucsupport.github.io/blog/)
日本の Unified Communications サポートチームより、Teams や Skype for Business について、よくお問い合わせをいただく情報や、技術者のみなさまに役立つ情報を配信いたします。

![Teams](https://user-images.githubusercontent.com/77912147/113543016-78847a80-9620-11eb-904d-bc47c16196f6.jpg)

**Comment by juntakata** [comment]
Update completed. Closing the issue.
